---

- name: Create host inventory
  hosts: localhost

  vars:
    system_type: "{{ current_system if current_system is defined else 'None' }}"
    default_email: "{{ current_email if current_email is defined else 'home.doing840@passmail.net' }}"
    default_get_mac_apps: "{{ true if 'Darwin' in system_type else false }}"
    default_vault_password: "{{ lookup('community.general.random_words', numwords=5, delimiter='-', case='capitalize') }}"

  vars_prompt:
    - name: vault_password
      prompt: Create Vault vault_password
      unsafe: true
      confirm: true
      default: "{{ default_vault_password }}"

    - name: hostname
      prompt: Enter system hostname
      private: false
      default: edace

    - name: email
      prompt: Enter email address
      private: false
      default: "{{ default_email }}"
    
    - name: clone_personal_repos
      prompt: Clone all personal repos (True|False)
      private: false
      default: true

    - name: upload_ssh_key_github
      prompt: Upload SSH Key to Github (True|False)
      private: false
      default: true

    - name: install_mac_apps
      prompt: Install apps from the Mac App Store (True|False)
      private: false
      default: false

    - name: work_system
      prompt: Install employer settings and scripts (True|False)
      private: false
      default: false

    - name: gh_token_personal
      prompt: Path to Github personal gh_token_personal
      private: true
      confirm: true
      default: "/home/{{ lookup('env', 'USER') }}/.ssh/id_rsa.pub"

  tasks:
    - name: Create Vault File
      ansible.builtin.copy:
        content: "{{ vault_password }}"
        dest: "{{ ansible_user_dir }}/.ansible/vault"
        mode: 0400
    
    - name: Create inventory
      vars:
        rsa_encrypted: "{{ lookup('community.general.random_words', numwords=5, delimiter='-', case='capitalize') | ansible.builtin.vault(vault_password) }}"
        ed25519_encryped: "{{ lookup('community.general.random_words', numwords=5, delimiter='-', case='capitalize') | ansible.builtin.vault(vault_password) }}" 
        gh_token_work_encrypted: "{{ gh_token_work | ansible.builtin.vault(vault_password) }}"
        gh_token_personal_encrypted: "{{ gh_token_personal | ansible.builtin.vault(vault_password) }}"

      ansible.builtin.template:
        src: inventory.yml.j2
        dest: "{{ ansible_user_dir }}/.ansible/inventory.yml"
        decrypt: false
        mode: 0755
