---
- name: Add Visual Studio Code Repo
  ansible.builtin.yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: true
    enabled: true
  become: yes

- name: Install
  ansible.builtin.dnf:
    state: present
    name:
      - code
  become: yes
