---
- hosts: localhost
  connection: local
  become: true

  tasks:
  # - name: install packages
  #   dnf:
  #     name:
  #       - htop
  #       - dnf-utils
  #       - gh
  #       - fzf
  #       - jq
  #       - python3
  #       - python3-devel
  #       - tree
  #       - wget

  - name: set roles
    set_fact:
      roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
    tags:
      - always

  - name: display roles
    debug: "var=roles"
    tags:
      - always

  - name: Run roles
    include_role:
      apply:
        tags:
          - "{{ roles_item }}"
      name: "{{ roles_item }}"
    loop_control:
      loop_var: roles_item
    with_items: "{{ roles }}"
    tags:
      - always
